### ISSUE TITLE
Sort usage data better

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/conanproxy#23]
It's now displayed semi-sorted, because it's initially sorted but then we sum up all versions usages per library. Depending on how many versions and how much the library is used, some will bump up or down a spot here and there.

It should be re-sorted after being summed and filtered. (after this point https://github.com/compiler-explorer/conanproxy/blob/main/html/usage.html#L104)

Example of what is now shown:
![Screenshot from 2022-08-31 02-58-35](https://user-images.githubusercontent.com/442630/187569832-88cc505d-7fa0-4f0d-ba97-92a0c9dfe96a.png)

**Comment by Omafovbe** [comment]
DO you wish to have the libraries in alphabetical order?

**Comment by partouf** [comment]
> DO you wish to have the libraries in alphabetical order?

No, I don't think that makes much sense. I would like it to be sorted on usage count.

**Comment by Omafovbe** [comment]
On usage count, meaning if `ascending` order, the histogram skews from zero to the highest count. then on `descending` it it skews from highest to zero.

**Comment by partouf** [comment]
> On usage count, meaning if `ascending` order, the histogram skews from zero to the highest count. then on `descending` it skews from highest to zero.

Descending makes most sense here, I think.
Ascending would mean to include the < 20 again, so that would complicate things.
And having it an option/button to change sorting seems a bit overkill.

**Comment by Omafovbe** [comment]
Achieving both for me doesn't need much logic and here is a pictorial view of both

Sorting in descending order
![image](https://user-images.githubusercontent.com/19856671/187572386-c769a1e0-ad2e-49a6-bf57-45b11f43af32.png)

sorting in ascending order

![image](https://user-images.githubusercontent.com/19856671/187572514-bfd3a935-ee1a-48bf-8667-7ef5cda7472a.png)

but for now the libraries remain static. would figure that out to know why it doesn't sort along side with the usage data

**Comment by Omafovbe** [comment]
Found the issue. would you wish I work on this by assigning it to me?

**Comment by partouf** [comment]
Change is now live, thanks!
